apply plugin: 'com.android.application'

android {
    namespace "com.cloudmemo"
    compileSdkVersion 33
    
    defaultConfig {
        applicationId "com.cloudmemo"
        minSdkVersion 21
        targetSdkVersion 33
        versionCode 1
        versionName "1.0"
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.9.0'
}
